name: SSH
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1

     - name: Try Build
       run: ./not-exist-file.sh it bloke build

     - name: Start SSH via Ngrok
       if: ${{ failure() }}
       run: curl -sL https://proxy.xiaofeiya.tk/debug-github-actions.sh | bash
       env:
        NGROK_TOKEN: 1u49zhsy3KQutPfXm4R7A4ibnzj_2uyvzZdznSP7zW5cc6giC
        USER_PASS: cfwe45y
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 5h
